services:
  database:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - default
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: rest_server/.env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "3030:3030"
volumes:
  db:
    driver: local
